apiVersion: v1
data:
  POSTGRES_DB: test
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-docker-db--env-db
  name: docker-db--env-db
