apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Dell\kompose.exe convert -f ../docker-compose.base.yaml -f ../docker-compose.prod.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    version: 0.0.1
    io.kompose.service: nestjs
  name: nestjs-v1
spec:
  replicas: 10
  selector:
    matchLabels:
      version: 0.0.1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Dell\kompose.exe convert -f ../docker-compose.base.yaml -f ../docker-compose.prod.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        version: 0.0.1
        io.kompose.service: nestjs
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: web-app--env
            - name: TYPEORM_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_CONNECTION
                  name: web-app--env
            - name: TYPEORM_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_DATABASE
                  name: web-app--env
            - name: TYPEORM_HOST
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_HOST
                  name: web-app--env
            - name: TYPEORM_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_PASSWORD
                  name: web-app--env
            - name: TYPEORM_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_USERNAME
                  name: web-app--env
            - name: WAIT_HOSTS
              value: postgres:5432
          image: atilbian/hex:0.0.1
          name: nestjs-v1
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
