apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\INRIA\Kompose\kompose.exe convert -f ../docker-compose.base.yaml -f ../docker-compose.prod.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
