apiVersion: v1
data:
  JWT_SECRET: '!ChangeMe!'
  TYPEORM_CONNECTION: postgres
  TYPEORM_DATABASE: test
  TYPEORM_HOST: postgres
  TYPEORM_PASSWORD: postgres
  TYPEORM_USERNAME: postgres
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nestjs-web-app--env
  name: web-app--env
