version: "3"
services:

  nestjs:
    container_name: nestjs
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
    env_file:
      - ./web-app/.env

  postgres:
    container_name: postgres
    image: postgres:10.4
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.docker/db/.env.db
