version: "3"
services:

  nestjs:
    image: atilbian/hex:0.0.1
    expose:
      - 3000

  postgres:
    volumes:
      - db-data-prod:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: atilbian/hex-nginx:0.0.1
    ports:
      - 80:80
    depends_on:
      - nestjs
    restart: always

volumes:
  db-data-prod:
