version: "3"
services:
  nestjs:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./web-app/:/usr/web-app/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    env_file:
      - ./.docker/pgadmin/.env.pgadmin
    ports:
      - 8080:80
    depends_on:
      - postgres

  react-admin:
    container_name: react-admin
    build:
      context: ./admin-app/
      dockerfile: ./Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./admin-app/:/usr/admin-app/
